services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: quiz
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
  app:
    build: .
    restart: unless-stopped
    ports:
    - "3000:3000"
    env_file:
    - .env
    volumes:
      - uploads:/app/public/uploads
volumes:
  dbdata:
  uploads:
